{
 "title": "Metricas Dead-by-cloud",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Number of calls to login endpoint in last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "login_requests_total" }
   ]
  },
  {
   "title": "Number of calls to signup endpoint in last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "signup_requests_total" }
   ]
  },
  {
   "title": "Number of calls to home endpoint in last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "home_requests_total" }
   ]
  },
  {
   "title": "Number of calls to public endpoint in last hour",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "public_requests_total" }
   ]
  },
  {
   "title": "CPU usage percent",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_percent{instance='deadbycloud.192.168.49.2.nip.io:80',job='flask-pastebin'}"
    }
   ]
  },
  {
   "title": "Memory usage MB",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(memory_usage_bytes{instance='deadbycloud.192.168.49.2.nip.io:80',job='flask-pastebin'}[30s])/1000000"
    }
   ]
  }
 ]
}