global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - "prometheus_rules.yaml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['172.17.0.1:9090']

  - job_name: 'flask-pastebin'
    static_configs:
    - targets: ['172.17.0.1:5000']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"